name: study_buddy
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  intl: ^0.17.0
  path: ^1.8.3
  persistent_bottom_nav_bar: ^5.0.2
  sqflite: ^2.3.0
  supabase_flutter: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.7
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-Bold.ttf
          weight: 700

  assets:
    - assets/logo/
    - assets/backgrounds/
    - assets/images/
    - assets/icons/
    - assets/
